services:
  link-service:
    build: ./
    tty: true
    stdin_open: true
    volumes:
      - ./:/src # для разработки, при изменении файлов не нужно пересобирать образ
    working_dir: /src
    ports:
      - 8000:8000
  
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5433:5432"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - db